apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: sensuy/hello-go:v5.3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
        ##Explo utilizando o configmap inteiro.
        envFrom:
          - configMapRef:
             name: goserver-env
          - secretRef:
             name: goserver-secret
        volumeMounts:
          - mountPath: go/myfamily
            name: config
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: configmap-family
          items:
            - key: members
              path: "family.txt"
        ##Explo utilizando as variaveis de ambiente uma a uma.
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: NAME
        #   - name: AGE
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: AGE
